# Generated by Django 5.1 on 2025-07-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlabs',
            name='url',
            field=models.CharField(default='', max_length=32, unique=True),
            preserve_default=False,
        ),
    ]
